---
title: "R"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE,comment = "")
```

```{r}
pkgs <- c("psych", "table1", "knitr", "tidyverse", "janitor", "broom",
          "patchwork", "ggcorrplot", "gridExtra", "ggstatsplot",
          "caret", "randomForest", "e1071", "kernlab", "neuralnet", "pROC",
          "nnet", "NeuralNetTools", "ROSE", "rpart", "xgboost",
          "shapviz", "kernelshap", "DiagrammeR")
install.packages(pkgs[!pkgs %in% installed.packages()[,"Package"]],
                 repos = "https://cran.r-project.org")
```

```{r}
library(psych)
library(table1)
library(knitr)   #
library(tidyverse)
```

```{r}
df <- read.csv("online_shoppers_intention.csv")
str(df)
```

```{r}
summary(df)
```


```{r}
options(scipen = 100)
numeric_vars <- c("Administrative", "Administrative_Duration", "Informational",
                  "Informational_Duration", "ProductRelated", "ProductRelated_Duration",
                  "BounceRates", "ExitRates", "PageValues", "SpecialDay")
desc_numeric <- df %>%
  select(all_of(numeric_vars))
quality_numeric<- function(x){
  m1<-c()
  m2<-c()
  m3<-c()
  m4<-c()
  m3_r<-c()
  m3_l<-c()
  m3_m <- c()
  options(digits=2)
  for (i in 1:ncol(x)){
    m1<- c(m1,min(x[[i]],na.rm = T))
    m2<- c(m2,max(x[[i]],na.rm = T))
    m3<- c(m3,mean(x[[i]],na.rm = T))
    m4<- c(m4,median(x[[i]],na.rm = T))
  }
  result<- cbind(m1,m2,m3,m4)
  rownames(result)<- names(x)
  colnames(result)<- c("Min","Max","Mean","Median")
  result<- as.data.frame(result)
  return(result)
}
quality_numeric(desc_numeric)
```

```{r}
# Convert to categorical variables
categorical_vars <- c("Month", "OperatingSystems", "Browser", "Region", "TrafficType",
                      "VisitorType", "Weekend", "Revenue")
df[categorical_vars] <- lapply(df[categorical_vars], as.factor)
```

```{r}
library(janitor)
df %>%
  tabyl(Revenue) %>%
  adorn_totals("row") %>%
  adorn_pct_formatting()
```


```{r}
library(broom)
tidy(chisq.test(df$Region,df$Revenue))
```
```{r}
tidy(chisq.test(df$VisitorType,df$Revenue))
```


```{r}
library(patchwork)
p1 <- ggplot(df, aes(x = Revenue, y = Administrative)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7) +
    labs(title = paste("Boxplot of", "Administrative", "by Revenue"), x = "Purchase", y = var) +
    theme_minimal() +
    scale_x_discrete(labels = c("No", "Yes"))+
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
p2 <- ggplot(df, aes(x = Revenue, y = Administrative_Duration)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7) +
    labs(title = paste("Boxplot of", "Administrative Duration", "by Revenue"), x = "Purchase", y = var) +
    theme_minimal() +
    scale_x_discrete(labels = c("No", "Yes"))+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
p3 <- ggplot(df, aes(x = Revenue, y = Informational_Duration)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7) +
    labs(title = paste("Boxplot of", "Informational Duration", "by Revenue"), x = "Purchase", y = var) +
    theme_minimal() +
    scale_x_discrete(labels = c("No", "Yes"))+
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
p4 <- ggplot(df, aes(x = Revenue, y = ProductRelated)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7) +
    labs(title = paste("Boxplot of", "ProductRelated", "by Revenue"), x = "Purchase", y = var) +
    theme_minimal() +
    scale_x_discrete(labels = c("No", "Yes"))+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
p5 <- ggplot(df, aes(x = Revenue, y = ProductRelated_Duration)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7) +
    labs(title = paste("Boxplot of", "ProductRelated Duration", "by Revenue"), x = "Purchase", y = var) +
    theme_minimal() +
    scale_x_discrete(labels = c("No", "Yes"))+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
p6 <- ggplot(df, aes(x = Revenue, y = BounceRates)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7) +
    labs(title = paste("Boxplot of", "BounceRates", "by Revenue"), x = "Purchase", y = var) +
    theme_minimal() +
    scale_x_discrete(labels = c("No", "Yes"))+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
p7 <- ggplot(df, aes(x = Revenue, y = ExitRates)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7) +
    labs(title = paste("Boxplot of", "ExitRates", "by Revenue"), x = "Purchase", y = var) +
    theme_minimal() +
    scale_x_discrete(labels = c("No", "Yes"))+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
p8 <- ggplot(df, aes(x = Revenue, y = PageValues)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7) +
    labs(title = paste("Boxplot of", "PageValues", "by Revenue"), x = "Purchase", y = var) +
    theme_minimal() +
    scale_x_discrete(labels = c("No", "Yes"))+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
(p1+p2+p3+p4)/(p5+p6+p7+p8)
```

```{r}
library(ggcorrplot)
corr <- desc_numeric %>% cor() %>% round(2)
ggcorrplot(corr,lab = TRUE,type = "lower",
           method = "circle",
           colors = c("tomato2","white","springgreen3"),
           title = "Correlation coefficient diagram",lab_size = 2,
           ggtheme = theme_bw())+
  theme(axis.text = element_text(family = "serif",size = 20),
        axis.title = element_text(family = "serif",size = 20))+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
bar_plot_list <- list()
for (cat_var in categorical_vars) {
  p <- ggplot(df, aes_string(x = cat_var)) +
    geom_bar(fill = "steelblue", alpha = 0.8) +
    labs(title = paste("Distribution of", cat_var),
         x = cat_var, y = "Count") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
  bar_plot_list[[cat_var]] <- p
}

library(gridExtra)
grid.arrange(bar_plot_list[["Month"]], bar_plot_list[["VisitorType"]],
             bar_plot_list[["Weekend"]], bar_plot_list[["Revenue"]], ncol = 2)
```


```{r}
library(ggstatsplot)
ggbetweenstats(data = df, x = Revenue, y = ProductRelated_Duration)
```


```{r}
ggpiestats(data = df, x = Revenue, y = VisitorType)
```


```{r}
ggpiestats(data = df, x = Revenue, y = Weekend)
```


# ML

```{r}
library(caret)
library(randomForest)
library(e1071)           # SVM
library(kernlab)          # SVM (alternative)
library(neuralnet)
library(pROC)
```

```{r}
df$Revenue <- ifelse(df$Revenue == TRUE,"Yes","No")
df$Revenue <- factor(df$Revenue)
df$TrafficType <- ifelse(df$TrafficType == 1,"Type One",ifelse(df$TrafficType == 2,"Type Two","Other types"))
df$TrafficType <- factor(df$TrafficType)
df$Browser<- ifelse(df$Browser == 1,"Browser Type 1",ifelse(df$Browser == 2,"Browser Type 2","Others"))
df$Browser <- factor(df$Browser)
df$OperatingSystems <- ifelse(df$OperatingSystems %in% c(1,2,3),df$OperatingSystems,"Others")
df$OperatingSystems <- factor(df$OperatingSystems)
```


# Data partitioning and balancing processing

```{r}
set.seed(502)
ind <- sample(2, nrow(df), replace = TRUE, prob = c(0.7, 0.3))#相当于生成ind列
train_data <- df[ind == 1, ]#训练数据
test_data <- df[ind == 2, ]#测试数据
```

```{r}
table(train_data$Revenue)
```

```{r}
library(ROSE)
train_data <- ovun.sample(Revenue ~ ., data = train_data, method = "both", p=0.5, N=nrow(train_data), seed = 1)$data
table(train_data$Revenue)
```


```{r}
# Extract features and target variables
X_train <- train_data %>% select(-Revenue)
y_train <- train_data$Revenue
X_test <- test_data %>% select(-Revenue)
y_test <- test_data$Revenue
```

# Decision tree model

```{r}
library(rpart)
tree_model <- rpart(Revenue ~ ., data = train_data, method = "class")
tree_pred <- predict(tree_model, newdata = test_data, type = "class")
```


# Logistic regression model

```{r}
logit_model <- glm(Revenue ~ ., data = train_data, family = binomial)
logit_pred_prob <- predict(logit_model, newdata = test_data, type = "response")
logit_pred <- factor(ifelse(logit_pred_prob > 0.5, "Yes", "No"))
```

# Random forest model

```{r}
library(e1071)
library(randomForest)
set.seed(1)
rfmodel <- tune.randomForest(Revenue ~ ., data = train_data,
                              nodesize = c(4:7),
                              mtry = c(2,4,6),
                              ntree = c(10,20))
rfmodel
```


```{r}
rf_pred <- predict(rfmodel$best.model, newdata = test_data)
```

# SVM

```{r}
svm_model <- svm(Revenue ~ ., data = train_data, kernel = "radial", probability = TRUE)
svm_pred <- predict(svm_model, newdata = test_data)
```

# Neural network

```{r}
library(nnet)
nnetmodel <- nnet(Revenue ~ ., data = train_data,
           size = c(5), # indicates the number of nodes in the shadow layer
           rang = 0.1,
           decay = 5e-2,
           maxit = 50)
```

```{r}
nnet_pred_raw <- predict(nnetmodel, newdata = test_data, type = "class")
nnet_pred <- factor(nnet_pred_raw, levels = c("No", "Yes"))
```


```{r}
# Draw the model, with a single hidden layer meaning of 5 nodes
library(NeuralNetTools)
plotnet(nnetmodel)
```


```{r}
# Obtain the relative importance of input variables in neural networks through the garson algorithm
garson(nnetmodel)
```


# Xgboost


```{r}
grid<-expand.grid(nrounds=c(10,20),
                  colsample_bytree=1,#
                  min_child_weight=1,#
                  eta=c(0.01,0.1),
                  gamma=c(0.5,0.25),
                  subsample=0.5,
                  max_depth=c(3,4))
cntrl <- trainControl(
  method = "cv",
  number = 2, #
  verboseIter = FALSE,
  returnData = FALSE,
  returnResamp = "final",
  classProbs = TRUE,
  summaryFunction = twoClassSummary
)
set.seed(123)
train.xgb<-train(Revenue~.,
                 data =train_data,
                 trControl=cntrl,
                 tuneGrid=grid,
                 metric = "ROC",
                 method="xgbTree")
```

```{r}
library(xgboost)
xgb.plot.tree(model = train.xgb$finalModel, trees = 1)
```


```{r}
# 得到变量重要性
importance_matrix <- xgb.importance(model = train.xgb$finalModel)
xgb.plot.importance(importance_matrix)
```


```{r}
xgb_pred <- predict(train.xgb,newdata = test_data)
```


```{r}
evaluate_model <- function(pred, true_label, name) {
  cm <- confusionMatrix(factor(pred), factor(true_label))
  test11 <- ifelse(true_label == "Yes",1,0)
  pre11 <- ifelse(pred == "Yes",1,0)
  rocobj<-roc(test11,pre11)
  #Get the value of AUC
  auc1<-auc(test11,pre11)
  list(
    accuracy = cm$overall['Accuracy'],
    precision = cm$byClass['Precision'],
    recall = cm$byClass['Recall'],
    f1 = cm$byClass['F1'],
    auc = auc1
    # auc = as.numeric(auc(as.numeric(pred)-1, as.numeric(y_test)-1))
  )
}
```


```{r}
results <- list()
results$Tree <- evaluate_model(tree_pred, y_test, "Decision Tree")
results$Logistic <- evaluate_model(logit_pred, y_test, "Logistic Regression")
results$RF <- evaluate_model(rf_pred, y_test, "Random Forest")
results$SVM <- evaluate_model(svm_pred, y_test, "SVM")
results$NET <- evaluate_model(nnet_pred, y_test, "Neural Network")
results$XGB <- evaluate_model(xgb_pred, y_test, "Xgboost")
```


```{r}
results_df <- data.frame(
  Model = names(results),
  Accuracy = sprintf("%.6f", sapply(results, function(x) x$accuracy)),
  Precision = sprintf("%.6f", sapply(results, function(x) x$precision)),
  Recall = sprintf("%.6f", sapply(results, function(x) x$recall)),
  F1 = sprintf("%.6f", sapply(results, function(x) x$f1)),
  AUC = sprintf("%.6f", sapply(results, function(x) x$auc))
)
results_df
```


```{r}
library(pROC)
test11 <- ifelse(y_test == "Yes",1,0)
pre11 <- ifelse(xgb_pred == "Yes",1,0)
rocobj<-roc(test11,pre11)
#Get the value of AUC
auc<-round(auc(test11,pre11),4)
ggroc(rocobj,color = "red",
      linetype = 1,
      size = 1,
      alpha = 1,
      legacy.axes = T)+
  geom_abline(intercept = 0,
              slope = 1,
              color = "grey",
              size = 1,
              linetype = 1)+
  labs(x = "False Postive Rate(1 - Specificity)",
       y = "True Positive Rate(Sensivity or Recall)")+
  annotate("text",x = 0.70,y = 0.30,
           label = paste("AUC =",auc),
           size = 5,
           family = "serif")+
  coord_cartesian(xlim = c(0,1),
                  ylim = c(0,1))+
  theme_bw()+
  theme(panel.background = element_rect(fill = "transparent"),
        axis.ticks.length = unit(0.4,"lines"),
        axis.ticks = element_line(color = "black"),
        axis.line = element_line(size = 0.5,
                                 colour = "black"),
        axis.title = element_text(colour = "black",
                                  size = 10,
                                  face = "bold"),
        axis.text = element_text(colour = "black",
                                 size = 10,
                                 face = "bold"),
        text = element_text(size = 8,
                            color = "black",
                            family = "serif"))
```


```{r}
library(shapviz)
library(kernelshap)
set.seed(1)
samindex<- sample(1:nrow(test_data),size = 100,replace = F)
pred_fun <- function(model, newdata) {
  predict(model, newdata = newdata, type = "prob")
}
s <- kernelshap(train.xgb, test_data[samindex,] |> select(-Revenue),
                bg_X = test_data[samindex,], pred_fun = pred_fun)
sv <- shapviz(s)
```

```{r}
sv_importance(sv$Yes, kind = "bee")+theme_minimal()+
  labs(x="SHAP value(impact on model output)")+
  theme_classic()+
  theme(axis.text = element_text(family = "serif",size = 14),
        axis.title = element_text(family = "serif",size = 14),
        legend.text = element_text(family = "serif",size = 14))
```


```{r}
sv_importance(sv$Yes)+theme_bw()+
  scale_x_continuous(expand = c(0,0))+
  labs(x="mean(|SHAP values|) (average impact on model output)")+
  theme_classic()+
  theme(axis.text = element_text(family = "serif",size = 14),
        axis.title = element_text(family = "serif",size = 14),
        legend.text = element_text(family = "serif",size = 14))
```


```{r}
sv_waterfall(sv$Yes, row_id = 1) +
  theme(axis.text = element_text(size = 11))
```



```{r}
sv_force(sv$Yes, row_id = 10)
```
